### ISSUE TITLE
FRAME ERROR! Payload Mismatch

### ISSUE THREAD

**Issue by Delranon** [chester4444/esp-smartmeter#1]
Hallo, ich habe im Prinzip den gleichen Aufbau (Netz Burgenland, Freischaltung von RJ12 Port und MQTT Setup) und versuche das Skript auf einem NodeMCU zum laufen zu kriegen.

MQTT meldet brav IP usw. an den Server - jedoch bekome ich ein Payload Mismatch.
Laut der Framedescription habe ich das korrekte eingetragen, inkl. den Keys welche ich bekommen habe. 
Ich finde jedoch den Fehler nicht.
Ausserdem finde ich komisch das zwei verschiedene Payloads anscheinend versendet werden.

Fehlermeldung im LOG:

```
FRAME ERROR!
HDLC payload mismatch: 109 != 248
FRAME ERROR!
HDLC payload mismatch: 109 != 128
FRAME ERROR!
HDLC payload mismatch: 109 != 128
FRAME ERROR!
HDLC payload mismatch: 109 != 128
FRAME ERROR!
HDLC payload mismatch: 109 != 248
FRAME ERROR!
HDLC payload mismatch: 109 != 248
FRAME ERROR!
```

Meine Variablen:

```
#define HdlcDelimiter 0x7E // Terminator of data (and start of data as well)
//#define payloadSize 0x5A         // unencrypted frame size (between two 0x7E)
#define payloadSize 0x6D           // encrypted frame size (between two 0x7E) 76
byte msgBuffer[payloadSize];
unsigned long int lastTerminator = 0; // needed to detect a SOF (every 5 sec)
unsigned long int lastTransmitData = 0; // turn off publishing live data after a given time, save bandwith
#define TRANSMIT_LIVE_DATA_TIMEOUT 60000UL    // after a given time, switch of MQTT
```

Und mein Datenpaket schaut so aus:

`7E A0 6D CE FF 03 90 F1 E6 E7 20 DB 08 4C 47 5A 67 71 47 40 55 30 20 02 CC 39 73 18 1D 0A B0 A0 6F 32 AF 86 BA C2 88 F5 F4 86 DB D1 D3 17 17 7A 5C BA 1B 2F C3 9C 89 82 95 C9 01 99 2D FD 33 31 A3 90 10 09 A0 C4 2F 0B 36 B8 29 95 3F 83 B9 DD 92 17 D4 A7 0A A1 5B 97 9B 0A AA 98 E2 E9 9F 20 55 D7 FF 19 D2 C8 C4 12 6E 54 58 B1 7E`

Wenn ich die FrameDescription von Ihnen korrekt gelesen habe sollte es eig. so funktionieren.

Irgendein Ansatz wo der Fehler liegen könnte?

Danke

**Comment by chester4444** [comment]
`HDLC payload mismatch: 109 != 128`
bedeutet, dass 109 (0x6D) Zeichen tatsächlich empfangen wurden - soweit ok.
Das sollte mit dem 2. Byte (0x7E nicht mitgezählt) des Datenpakets übereinstimmen.

Dein Paket von oben hat 0x6D an 2. Stelle (ohne 0x7E gezählt) - soweit ok

Das Logging sagt aber, dass an 2. Stelle 0x80 (128) bzw 0xF8 drinnen steht
das passt nicht zu deinem Datenpaket.

aktiviere auf Zeile 592 das Logging mit `#if 1` und schick mal ein paar Pakete

**Comment by Delranon** [comment]
Hallo,

danke für die Antwort - #if 1 Logging hat mir sehr geholfen, dabei sah ich das "nur" 

```
0xF8, F8 0xF8, F8 0xF8, F8 0xF8, F8 0x80, 80 0xF8, F8 0xF8, F8 0xF8, F8 0x80, 80 0xF8, F8 0xF8, F8 0xF8, F8 0x80, 80 0xF8, F8 0xF8, F8 0x80, 80 
0xF8, F8 0x80, 80 0xF8, F8 0xF8, F8 0x80, 80 0x80, 80 0xF8, F8 0x80, 80 0xF8, F8 0xF8, F8 0x80, 80 0x80, 80 0x80, 80 0xF8, F8 0xF8, F8 0x80, 80 
0xF8, F8 0x80, 80 0xF8, F8 0xF8, F8 0xF8, F8 0xF8, F8 0xF8, F8 0xF8, F8 0x80, 80 0x80, 80 0x80, 80 0xF8, F8 0x80, 80 0xF8, F8 0x80, 80 0x80, 80 
0x80, 80 0x80, 80 0x80, 80 0xF8, F8 0xF8, F8 0xF8, F8 0x80, 80 0xF8, F8 0x80, 80 0xF8, F8 0x80, 80 0x80, 80 0x80, 80 0xF8, F8 0x80, 80 0xF8, F8 
0x80, 80 0x80, 80 0xF8, F8 0xF8, F8 0xF8, F8 0xF8, F8 0x80, 80 0x80, 80 0x80, 80 0x80, 80 0xF8, F8 0xF8, F8 0xF8, F8 0x80, 80 0x80, 80 0x80, 80 
0x80, 80 0x80, 80 0xF8, F8 0x80, 80 0xF8, F8 0xF8, F8 0x80, 80 0xF8, F8 0x80, 80 0xF8, F8 0xF8, F8 0xF8, F8 0x80, 80 0xF8, F8 0x80, 80 0x80, 80 
0x80, 80 0x80, 80 0xF8, F8 0xF8, F8 0x80, 80 0x80, 80 0xF8, F8 0xF8, F8 0xF8, F8 0xF8, F8 0x80, 80 0x80, 80 0xF8, F8 
HDLC payload mismatch: 109 != 248
```

zurück kam - was mich auf ein BAUD Problem hinwies. Nachdem ich

`#if defined (ESP8266)` 

auf 2400 geändert hatte kamen die richtigen Daten an. 
Jedoch hänge ich jetzt bei **Authentication Failed**:

`Authentication Failed

0F 00 03 B0 37 0C 07 E4 0B 1A 04 14 2B 32 FF 80 
00 00 02 0B 12 00 EA 12 00 EB 12 00 E9 12 00 C2 
12 01 0B 12 00 78 06 00 00 04 43 06 00 00 00 00 
06 01 9D A9 0F 06 00 00 00 00 09 08 33 30 30 31 
39 39 34 30 FF 5C 64 E2 2C 41 B5 29 5E `

Den Auth Key habe ich als Einzeiler von Energie Burgenland bekommen:

C0C1C2C3 usw. - insg. 32 Zeichen welche ich folgendermassen eingetragen habe:

`const uint8 e_auth_key[17] = { 0x00, 0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7` usw.

Gleiches mit dem Encryption Key. 
Oder gehört das anders?

Danke, lg

**Comment by chester4444** [comment]
Alles klar, 
schaut nicht schlecht aus, da du eine kürzere Info hast als ich, passt die Position des AUTH-tags (bei mir 104) nicht

schreib mal auf Zeile 535 anstatt 
`memcpy(gcm_tg, &buf[104], sizeof(gcm_tg));`
das hier
`memcpy(gcm_tg, &buf[payloadSize-14], sizeof(gcm_tg));`

**Comment by Delranon** [comment]
Immer noch der Fehler:

`uthentication Failed

0F 00 03 B2 67 0C 07 E4 0B 1A 04 15 1E 1E FF 80 
00 00 02 0B 12 00 EC 12 00 EB 12 00 E8 12 00 B6 
12 01 06 12 00 76 06 00 00 04 29 06 00 00 00 00 
06 01 9D AC 6F 06 00 00 00 00 09 08 33 30 30 31 
39 39 34 30 AC BA 32 AA 7E 7A CC 5C 8E 
A0 6D CE FF 03 13 90 F1 E6 E7 00 DB 08 4C 47 5A 
67 71 11 47 40 55 30 00 03 B2 68 0D B0 8F 35 9E 
8A DF E0 EA 4D AA D0 78 7D D0 2D EA EC 78 41 15 
0B 82 9C ED 8D B1 96 D6 92 3A AB A1 C2 7F 07 55 
4F A9 25 C5 11 89 E7 64 BC 06 52 6D 1B 9B 1F B0 
B0 78 40 9F D1 37 3D E0 C5 A6 4E 40 0F F6 FE 89 
2C 5B C7 62 39 CA FE F3 64 B4 F2 FE 6B 
4C 47 5A 67 71 11 47 40 00 03 B2 68 
0D B0 8F 35 9E 8A DF E0 EA 4D AA D0 78 7D D0 2D 
EA EC 78 41 15 0B 82 9C ED 8D B1 96 D6 92 3A AB 
A1 C2 7F 07 55 4F A9 25 C5 11 89 E7 64 BC 06 52 
6D 1B 9B 1F B0 B0 78 40 9F D1 37 3D E0 C5 A6 4E 
40 0F F6 FE 89 2C 5B C7 62 39 CA FE F3 
89 2C 5B C7 62 39 CA FE F3 64 B4 F2 

Authentication Failed

0F 00 03 B2 68 0C 07 E4 0B 1A 04 15 1E 23 FF 80 
00 00 02 0B 12 00 EC 12 00 EB 12 00 E9 12 01 32 
12 01 0A 12 00 77 06 00 00 05 13 06 00 00 00 00 
06 01 9D AC 71 06 00 00 00 00 09 08 33 30 30 31 
39 39 34 30 22 58 BD 6E 5F 82 1A DD C6 
A0 6D CE FF 03 13 90 F1 E6 E7 00 DB 08 4C 47 5A 
67 71 11 47 40 55 30 00 03 B2 69 34 10 C5 23 93 
6D C4 60 D3 34 3F 49 70 08 ED 1C 68 77 FD C9 8A 
68 E7 7F 0F 7D 9F CA 61 5D B5 72 44 AB EE 4B 39 
4F C1 FF B0 67 23 0D 05 78 C5 CF 6B 59 61 B8 E8 
FC 84 D1 B7 F6 CD 31 C5 AA B9 07 21 FD 72 72 1E 
1C A9 B1 8A E7 A7 77 7B 5E B3 A9 F0 B0 
4C 47 5A 67 71 11 47 40 00 03 B2 69 
34 10 C5 23 93 6D C4 60 D3 34 3F 49 70 08 ED 1C 
68 77 FD C9 8A 68 E7 7F 0F 7D 9F CA 61 5D B5 72 
44 AB EE 4B 39 4F C1 FF B0 67 23 0D 05 78 C5 CF 
6B 59 61 B8 E8 FC 84 D1 B7 F6 CD 31 C5 AA B9 07 
21 FD 72 72 1E 1C A9 B1 8A E7 A7 77 7B 
1E 1C A9 B1 8A E7 A7 77 7B 5E B3 A9 `

Encrypted wird übertragen via MQTT, Live aber leider nicht

**Comment by chester4444** [comment]
MQTT schauen wir uns nachher an,
versuch mal folgendes
`// cipher-data
uint8_t gcm_ct[77];
uint8_t gcm_pt[77];`

die 77 auf 68 (beide)

**Comment by Delranon** [comment]
Jep - das wars

Authentication OK

Und ich bekomm die Daten in MQTT gepushed.

Es funktioniert - ich danke dir vielmals

**Comment by chester4444** [comment]
Sehr schön. 
Die "hard-coded" Nummern werde ich rausnehmen, ich überlege mir was felxibleres
Ich dachte nicht, dass das wer brauchen köntne, ich pushe demnächst eine verbesserte Version,

Falls dann irgendwann ein Zählerupdate kommt, und du ein längeres/kürzeres Paket bekommst,
sollte das dann kein Problem mehr sein.

**Comment by Delranon** [comment]
Danke nochmal - ich weiß es ist sehr speziell und deswegen bin ich so froh das du ziemlich genau den gleichen Aufbau hast.
Das Auslesen wäre ja noch einigermaßen gegangen, aber beim decoden hätte es mich aufgeschmissen.

Solltest du irgendwelche Daten oder sonstiges brauchen kann ich gerne, sofern möglich aushelfen.

**Comment by chester4444** [comment]
> Solltest du irgendwelche Daten oder sonstiges brauchen kann ich gerne, sofern möglich aushelfen.

Hi, ich hab nun eine neue Version eingecheckt, die flexibler im Umgang mit verschiedenen Framelängen sein sollte - wäre nett, wenn du sie testen könntest.

Man muss keinen Code anpassen, einfach auschecken und testen, sollte alles funktionieren.
