### ISSUE TITLE
payload mismatch nach zwei (beschädigten) frames

### ISSUE THREAD

**Issue by makiele** [chester4444/esp-smartmeter#2]
Hi Chester,

vielen dank nochmal für deinen einsatz und deine wirklich hilfreichen tools.
momentan warte ich noch immer auf antwort der WN, habe mich aber in der zwischenzeit an deine esp-smartmeter lösung geschmissen.

ich verwende einen wemos d1 mini - photodiode angeschlossen an GND und D1.
wenn ich das ganze an den smart meter klemme scheint aber nur blödsinn zu kommen (der frame wirkt beschädigt) und nach zwei oder drei beschädigten frames kommt dann zuerst einmalig
`HDLC payload mismatch: 2 != 0`

gefolgt von diesen zwei meldungen, die bis zu einem neustart sich permanent wiederholen
`HDLC payload mismatch: 1 != 0`
`FRAME ERROR! - baudrate ok?`

das wurde ja bedeuten, dass er plötzlich gar keine frames mehr bekommt - nur weshalb?
über usb-ttl und photodiode sind die frames intakt.

any idea, was ich falsch mache.
danke ung lg

**Comment by makiele** [comment]
Hier noch der Debug-Output
Nach dem ersten` HDLC payload mismatch: 1 != 0` geht das unendlich so weiter

```
20 C0 80 C0 CE 78 7C 00 C0 FF 7C 00 46 8C FE 02 
02 30 38 C4 C6 00 92 00 08 06 10 46 62 02 4C 30 
0E 00 00 00 80 C0 C8 C8 42 88 02 04 20 00 18 02 
20 40 00 00 60 00 E0 04 08 02 06 18 00 10 04 00 
88 CC 0E 0E 00 04 F0 02 48 92 7C 30 80 00 42 00 
00 02 00 0E 42 84 10 F8 8E C0 04 00 10 00 9E 04 
78 90 08 08 60 80 80 20 06 00 10 00 00 84 30 30 
02 60 7C 77 73 FF 03 13 38 BD E6 E7 00 DB 08 4C 
47 5A 67 73 43 6E B9 4F 20 00 25 CA E6 AA 15 90 
F6 EF C0 83 B4 A2 A2 B6 FA 57 A5 AB FA 9B 77 9A 
53 60 08 6D 03 59 C0 38 02 65 CE 00 00 5C F8 80 
00 80 E0 0C 20 00 00 00 00 00 E4 72 C2 C0 38 12 

HDLC header CRC mismatch
FRAME ERROR! - baudrate ok?

FE 06 7C 7C 00 46 
HDLC header CRC mismatch
FRAME ERROR! - baudrate ok?

04 32 02 00 00 00 3E 04 E4 3E 00 1E 98 18 78 04 
00 00 0C C2 20 C0 3E 18 88 00 00 06 00 00 00 9C 
06 82 10 10 02 20 7C 7C 7C 00 46 8C FE 02 02 30 
38 C4 
HDLC header CRC mismatch
FRAME ERROR! - baudrate ok?


HDLC payload mismatch: 2 != 0
FRAME ERROR! - baudrate ok?


HDLC payload mismatch: 1 != 0
FRAME ERROR! - baudrate ok?


HDLC payload mismatch: 1 != 0
FRAME ERROR! - baudrate ok?


HDLC payload mismatch: 1 != 0
FRAME ERROR! - baudrate ok?
```

**Comment by chester4444** [comment]
aktiviere mal auf Zeile 669 mit `#if 1` mehr  debuggin-infos

**Comment by chester4444** [comment]
im größeren Block finden sich Fragmente eines Frames, hier zB.

```
   60 7C 77 73 FF 03 13 38 BD E6 E7 00 DB 08 4C 
47 5A 67 73 43 6E B9 4F 20 00 25 CA E6 AA 15 90 
F6 EF C0 83 B4 A2 A2 B6 FA 57 A5 AB FA 9B 77 9A 
53 60 08 6D 03 59 C0 38 02 65 CE 00 00 5C F8 80 
00 80 E0 0C 20 00 00 00 00 00 E4 72 C2 C0 38 12
```
die ersten 4 Bytes machen keinen Sinn, aber ab FF 03
schauts eigentlich aus wie ein HDLC Frame
`4C 47 5A` ist als LGZ zu lesen 
`4F` die Länge
`20`das Security-Byte
`00 25 CA E6` könnte der _nonce counter_ sein
aber wie gesagt, der Header ist korrupt.

Ist das Auge an der richtigen Position?
also 1. genau drüber und 2. nicht am falschen (da sind ja zwei Möglichkeiten)

**Comment by makiele** [comment]
danke für deinen input - ich könne heute das rätsel lösen -  der genutzte widerstand war defekt.
