### ISSUE TITLE
fehler nach einiger zeit im dauerbetrieb/live-modus

### ISSUE THREAD

**Issue by d3dahl** [chester4444/esp-smartmeter#3]
Hi!

nachdem die wiener netze einen neuen key zur verfügung gestellt haben, konnte ich die daten meines lzg e450 erfolgreich entschlüsseln. im zuge dessen bin ich auf dieses projekt gestoßen.

mittlerweile konnte ich `esp-smartmeter` mit einem wemos d1 mini nutzen und speise die daten per mqtt in home assistant ein.

um etwas mehr statistik zu erfassen, wollte ich nun esp-smartmeter auf "dauersendung" umstellen, also durchgehend daten per mqtt im live-modus übertragen lassen.

problem dabei: das programm scheint sich immer wieder nach unterschiedlichen zeitintervallen zu "verschlucken". wenn ich debugge, bekomme ich dann "`HDLC header CRC mismatch`" und "`HDLC payload mismatch: x != y`".  ab diesem moment werden diese fehler dann ca 100 mal pro sekunde geworfen bis ich einen neustart durchführe. für mich wirkt es so, als würde der wemos dann einfach einzelne bytes oder ein paar bytes als ganzen frame interpretieren. folglich liefert esp-smartmeter ab dem "verschlucken" auch keine daten mehr, bis ich neustarte.

meist kommen diese fehler erst nach 20 bis 40 minuten oder manchmal erst nach 2 stunden. mehr als zwei stunden hab ich bis jetzt nicht geschafft. nach einem neustart des wemos funktioniert sofort wieder alles und es geht normal weiter.

ganz selten "verschluckt" er sich direkt nach dem restart, wirft die genannten fehler und erst ein neuerlicher restart lässt ihn wieder für einige zeit normal laufen.

da mein zähler etwas abgelegen ist, habe ich jetzt mal versucht auch etwas debugging per mqtt zu betreiben, weiß aber nicht, an welchen stellen ich noch ansetzen könnte.

irgendwelche ideen, warum dieser fehler auftritt?
danke im voraus

**Comment by chester4444** [comment]
Ändere hier
https://github.com/chester4444/esp-smartmeter/blob/68a6cf67275ca70e575473d78cbe6afbb3f67ade/src/main.cpp#L643

auf 500

**Comment by d3dahl** [comment]
that did it - thanks
